# -*- coding: utf-8 -*-
"""corn_leaves_diesease.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1soaACje4Y8Z6DEmC8cO2Oj3-TyueNgqH
"""

! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

! kaggle datasets download -d qramkrishna/corn-leaf-infection-dataset

! unzip corn-leaf-infection-dataset.zip

import os
import tensorflow as tf
from tensorflow.keras import layers,models
import numpy 
import matplotlib.pyplot as plt
from tensorflow.keras.applications import VGG16
import cv2
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from glob import glob

directory='/content/Corn Disease detection'
categories=['Healthy corn','Infected']
for category in categories:
  path=os.path.join(directory,category)
  for image in os.listdir(path):
    img_array=cv2.imread(os.path.join(path,image))
    convt=cv2.cvtColor(img_array,cv2.COLOR_BGR2RGB)
    newarray=cv2.resize(convt,(1000,1000))
    plt.imshow(newarray)
    break
  break

len(os.listdir('/content/Corn Disease detection/Healthy corn'))

len(os.listdir('/content/Corn Disease detection/Infected'))

train_data_generator=ImageDataGenerator(rotation_range=0.2,width_shift_range=0.3,zoom_range=0.4,vertical_flip=True,fill_mode='nearest',shear_range=0.3)

train_data=train_data_generator.flow_from_directory(directory=directory,target_size=(1000,1000),shuffle=True,batch_size=30)

folders=glob(directory)
print(len(folders))

vgg=VGG16(input_shape=(1000,1000,3),weights='imagenet',include_top=False)

for layer in vgg.layers:
  layer.trainable=False

x=layers.Flatten()(vgg.output)
prediction=layers.Dense(1,activation='softmax')(x)
model=models.Model(inputs=vgg.input,outputs=prediction)

model.summary()

model.compile(loss='categorical_crossentropy',metrics=['accuracy'],optimizer='adam')

hist=model.fit(train_data,epochs=5)

