# -*- coding: utf-8 -*-
"""helperFunction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GncCPpEHmj3FAn80CvjFC9YQgekHiK3Y
"""

def findConv2dOutShape(H_in,W_in,conv,pool=2):
  # get conv arguments
  kernel_size=conv.kernel_size
  stride=conv.stride
  padding=conv.padding
  dilation=conv.dilation
  # Ref: https://pytorch.org/docs/stable/nn.html
  H_out=np.floor((H_in+2*padding[0]-dilation[0]*(kernel_size[0]-1)-1)/stride[0]+1)
  W_out=np.floor((W_in+2*padding[1]-dilation[1]*(kernel_size[1]-1)-1)/stride[1]+1)
  return int(H_out),int(W_out)

# example 
import torch.nn as nn
import numpy as np

findConv2dOutShape(39,39,conv=nn.Conv2d(in_channels=3,out_channels=10,stride=1,padding=0,kernel_size=3))



