# -*- coding: utf-8 -*-
"""Image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LVF6ylkBQJrkucfgOb7zT-bZiHyPuEdG
"""

! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

! kaggle datasets download -d tongpython/cat-and-dog

! unzip cat-and-dog.zip

train_path='/content/training_set/training_set'

import torch
import torch.nn as nn
import torchvision.datasets as datasets
import cv2
from torch.utils.data import Dataset, DataLoader
import os
import numpy as np
import matplotlib.pyplot as plt
from glob import glob

cats=glob(train_path+'/cats/*.jpg')
dogs=glob(train_path+'/dogs/*.jpg')
fpaths=cats+dogs
print(fpaths)

suman='/content/training_set/training_set/cats/cat.2580.jpg'
hari=suman.split('/')[-1].startswith('cat')
print(hari)

sum=[fpath.split('/')[-1] for fpath in fpaths]
print(sum)

data[200]

df_file={'img':[],
         'label':[]}
categories=['dogs','cats']
for category in categories:
  path=os.path.join(train_path,category)
  label=categories.index(category)
  for img in os.listdir(path):
    img_array=cv2.imread(os.path.join(path,img))
    df_file['img'].append(img)
    df_file['label'].append(label)

import pandas as pd
df=pd.DataFrame(df_file)
df.head()

df.value_counts()

df_hari=pd.read_csv('hari.csv')
df_hari.head()

df_hari.value_counts()

