# -*- coding: utf-8 -*-
"""CalculatingGradients.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AyLtw4siLysqZ0jU6dzfRNFp0KVelELq
"""

import torch

x=torch.rand(3,requires_grad=True)
print(x)
x.requires_grad_(False)
print(x)
y=x.detach()
print(y)
with torch.no_grad():
  y=x+2
  print(y)

weights=torch.ones(4,requires_grad=True)

for epoch in range(2):
  model_output=(weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

