# -*- coding: utf-8 -*-
"""imageaugmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XgEUYzbhlnPWAfGsqpY_BwdjC-o8fR53
"""

! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

! kaggle datasets download -d shaunthesheep/microsoft-catsvsdogs-dataset

! unzip microsoft-catsvsdogs-dataset.zip

from tensorflow.keras.preprocessing.image import ImageDataGenerator
import tensorflow as tf

data_path='/content/PetImages'
train_loader=ImageDataGenerator(rotation_range=0.1,width_shift_range=0.2,zoom_range=0.1,vertical_flip=True,fill_mode='nearest')

train_data=train_loader.flow_from_directory(directory=data_path,target_size=(500,500),batch_size=32,shuffle=True)

